# Generated by Django 4.1 on 2022-09-28 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolisttemplate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todolisttemplate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='todolisttemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
