# Generated by Django 4.1 on 2022-09-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todolisttemplate_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolisttemplate',
            name='isfinished',
        ),
    ]
